/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import communication.Communication;
import communication.Operation;
import communication.Request;
import communication.Response;
import domain.Message;
import domain.User;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import thread.ReceiverThread;
import ui.table.MessageTableModel;

/**
 *
 * @author Ognjen
 */
public class FrmMain extends javax.swing.JFrame {
    private User currentUser;
    private ReceiverThread receiverThread;
    // DODATO: Lista koja čuva sve poruke u memoriji klijenta
    private List<Message> allReceivedMessages = new ArrayList<>();
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMain.class.getName());

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }
    
    public FrmMain(User user){
        initComponents();
        this.currentUser = user;
        lblUser.setText("Ulogovani ste kao: " + user.getFirstName());
        
        // Pokretanje niti koja sluša server
        receiverThread = new ReceiverThread(this);
        receiverThread.start();
        
        // Postavljamo prazne modele na početku da ne bi bili "Title 1, Title 2..."
        tblPoslednje3.setModel(new MessageTableModel(new ArrayList<>()));
        tblOstale.setModel(new MessageTableModel(new ArrayList<>()));
        
        // inicijalno trazimo listu ulogovanih korisnika
        prepareView();
    }
    
    private void prepareView(){
        try {
            // zahtev serveru da nam posalje ko je sve online
            Request req = new Request(Operation.GET_LOGGED_USERS, null);
            Communication.getInstance().getSender().send(req);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Ovu metodu poziva ReceiverThread kada nesto stigne sa servera
    public void handleResponse(Response response){
       if (response.getResult() instanceof List) {
            List<User> ulogovani = (List<User>) response.getResult();
            cbKorisnici.removeAllItems();
            cbKorisnici.addItem("SVI"); // Ovde "SVI" ostaje String, zato je cbKorisnici<Object> ili <String>
            for (User u : ulogovani) {
                if (!u.equals(currentUser)) {
                    cbKorisnici.addItem(u.toString()); // Ili samo u, ako je combo box tipa User
                }
            }
        } else if (response.getResult() instanceof Message) {
            // ISPRAVLJENO: Dodavanje poruke u listu i osvežavanje
            Message m = (Message) response.getResult();
            allReceivedMessages.add(m);
            refreshMessageTables();
        }
    }
    
    private void refreshMessageTables() {
    List<Message> last3 = new ArrayList<>();
    List<Message> others = new ArrayList<>();

    int total = allReceivedMessages.size();
    
    if (total <= 3) {
        last3.addAll(allReceivedMessages);
    } else {
        // Poslednje 3 su na kraju liste
        last3 = allReceivedMessages.subList(total - 3, total);
        // Sve ostale su od početka do total - 3
        others = allReceivedMessages.subList(0, total - 3);
    }

    tblPoslednje3.setModel(new MessageTableModel(last3));
    tblOstale.setModel(new MessageTableModel(others));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        cbKorisnici = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPoslednje3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOstale = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPoruka = new javax.swing.JTextField();
        btnPosalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Poslednje 3 poruke:");

        tblPoslednje3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPoslednje3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPoslednje3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPoslednje3);

        jLabel3.setText("Ostale poruke:");

        tblOstale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblOstale);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel4.setText("Poruka:");

        btnPosalji.setText("Posalji");
        btnPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPosalji)
                    .addComponent(txtPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnPosalji)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addGap(18, 18, 18)
                        .addComponent(cbKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(cbKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiActionPerformed
        String tekst = txtPoruka.getText().trim();
        if (tekst.isEmpty()) return;
        
        if (tekst.length() > 200) {
            JOptionPane.showMessageDialog(this, "Poruka je predugacka");
            return;
        }

        // ISPRAVLJENO: Logika za određivanje primaoca
        Object selected = cbKorisnici.getSelectedItem();
        User primalac = null;
        Operation op = Operation.SEND_MESSAGE_ALL;

        if (selected instanceof User) {
            primalac = (User) selected;
            op = Operation.SEND_MESSAGE_PRIVATE;
        } else if (selected instanceof String && !selected.equals("SVI")) {
            // Ako ti je ComboBox pun Stringova, ovde moraš naći User objekat
            // ali je najbolje da cbKorisnici prima objekte
        }

        Message msg = new Message(currentUser, primalac, tekst, new Date());

        try {
            Communication.getInstance().getSender().send(new Request(op, msg));
            txtPoruka.setText(""); // Očisti polje nakon slanja
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnPosaljiActionPerformed

    private void tblPoslednje3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPoslednje3MouseClicked
        int row = tblPoslednje3.getSelectedRow();
        if(row != -1){
            MessageTableModel model = (MessageTableModel) tblPoslednje3.getModel();
            Message m = model.getMessageAt(row);
            JOptionPane.showMessageDialog(null, m.getText(), "Cela poruka", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tblPoslednje3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPosalji;
    private javax.swing.JComboBox<String> cbKorisnici;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTable tblOstale;
    private javax.swing.JTable tblPoslednje3;
    private javax.swing.JTextField txtPoruka;
    // End of variables declaration//GEN-END:variables
}
